### ISSUE TITLE
Tried to register two views with the same name ToolbarAndroid

### ISSUE THREAD

**Issue by marcelomunozr** [react-native-community/toolbar-android#15]
This is the problem i had https://github.com/oblador/react-native-vector-icons/issues/1193
The problem is in android only: "Tried to register two views with the same name ToolbarAndroid"
i already added by: yarn add @react-native-community/toolbar-android

```
@react-native-community/toolbar-android": "^0.1.0-rc.2
"react-native-vector-icons": "6.6.0"
```

I also tried:
`"react-native-vector-icons": "7.0.0"`
but persist the problem.

Where is this component register?
I need help my friends!

![image](https://user-images.githubusercontent.com/29933103/88674666-1601d480-d0b8-11ea-9802-9819e8d998e8.png)

**Comment by yohanceli** [comment]
@marcelomunozr  same problem, how to resolve it?

**Comment by marcelomunozr** [comment]
@yohanceli 
https://github.com/oblador/react-native-vector-icons/issues/1193#issuecomment-678868311
