### ISSUE TITLE
Npm 404 error

### ISSUE THREAD

**Issue by dsemennyuk** [react-native-community/toolbar-android#16]
`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@react-native-community%2ftoolbar-android - Not found
npm ERR! 404
npm ERR! 404  '@react-native-community/toolbar-android@0.1.0-rc.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/passwordis1234/.npm/_logs/2020-08-06T09_18_58_867Z-debug.log`

**Comment by navarroaxel** [comment]
The package installation is working, I think that this issue is related with this incident report:
`Issues accessing npmjs.com and installing scoped packages`
https://status.npmjs.org/incidents/cksjqc1w11v5?u=h3k0d3tk0b9y

**Comment by connectdotz** [comment]
this didn't seem to be a problem with this package. closing.
